# Generated by Django 3.1.7 on 2021-03-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('publications', models.CharField(max_length=200)),
                ('edition', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('no_of_copies', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.bookcategory')),
            ],
        ),
    ]
