# Generated by Django 3.1.7 on 2021-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_book_initial_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='initial_copies',
            field=models.IntegerField(),
        ),
    ]
