# Generated by Django 3.1.7 on 2021-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_auto_20210409_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(upload_to='book_pictures/'),
        ),
    ]
