# Generated by Django 3.1.7 on 2021-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('people_count', models.IntegerField()),
            ],
        ),
    ]
