# Generated by Django 3.1.7 on 2021-03-22 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
